package com.zws.model;

import javax.persistence.*;
import java.io.Serializable;

/**
 * generated by Generate model.groovy 
 * <p>Date: Thu Aug 15 10:45:19 CST 2019.</p>
 *
 * @author 0xe590b4
 */

@Entity
@Table ( name ="account" )
public class Account  implements Serializable {




	private Long id;

	private String name;

	private String head;

	private String username;

	private String passwd;

	private Long lastLoginTime;


    @Id
   	@Column(name = "id" )
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

    @Basic
   	@Column(name = "name" )
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

    @Basic
   	@Column(name = "head" )
	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

    @Basic
   	@Column(name = "username" )
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

    @Basic
   	@Column(name = "passwd" )
	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

    @Basic
   	@Column(name = "last_login_time" )
	public Long getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Long lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

}
