package com.zws.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.io.Serializable;

/**
 * generated by Generate model.groovy
 * <p>Date: Fri Aug 16 17:27:09 CST 2019.</p>
 *
 * @author 0xe590b4
 */

@Entity
@ApiModel("实例album" )
@Table ( name ="album" )
public class Album  implements Serializable {




	private Long id;

	/**
	 * 用户名
	 */
	@ApiModelProperty(value = "用户名")
	private Long accountId;

	/**
	 * 创建时间
	 */
	@ApiModelProperty(value = "创建时间")
	private Long createTime;

	/**
	 * 0: 正常 1: 删除
	 */
	@ApiModelProperty(value = "0: 正常 1: 删除")
	private Long isDelete;

	/**
	 * 封面图片链接
	 */
	@ApiModelProperty(value = "封面图片链接")
	private String cover;

	/**
	 * 日志
	 */
	@ApiModelProperty(value = "日志")
	private String record;


	@Id
	@Column(name = "id" )
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Basic
	@Column(name = "account_id" )
	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	@Basic
	@Column(name = "create_time" )
	public Long getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	@Basic
	@Column(name = "is_delete" )
	public Long getIsDelete() {
		return this.isDelete;
	}

	public void setIsDelete(Long isDelete) {
		this.isDelete = isDelete;
	}

	@Basic
	@Column(name = "cover" )
	public String getCover() {
		return this.cover;
	}

	public void setCover(String cover) {
		this.cover = cover;
	}

	@Basic
	@Column(name = "record" )
	public String getRecord() {
		return this.record;
	}

	public void setRecord(String record) {
		this.record = record;
	}

}
